const spokenContent = {

    comerFora: [
        { en: "I would like a table for two, please.", pt: "Gostaria de uma mesa para dois, por favor." },
        { en: "Can I see the menu?", pt: "Posso ver o cardápio?" },
        { en: "I will have the chicken, please.", pt: "Vou querer o frango, por favor." },
        { en: "What do you recommend?", pt: "O que você recomenda?" },
        { en: "Can I get this without onions?", pt: "Posso pedir isso sem cebolas?" },
        { en: "I am allergic to peanuts.", pt: "Sou alérgico a amendoim." },
        { en: "Is this dish spicy?", pt: "Esse prato é apimentado?" },
        { en: "Can we have separate checks?", pt: "Podemos ter contas separadas?" },
        { en: "Just water for me, thanks.", pt: "Só água para mim, obrigado." },
        { en: "Can I get this to go?", pt: "Posso pedir para viagem?" },
        { en: "Can I get the bill, please?", pt: "Posso pedir a conta, por favor?" },
        { en: "That was delicious!", pt: "Estava delicioso!" },
        { en: "Do you take credit cards?", pt: "Vocês aceitam cartões de crédito?" },
        { en: "What drinks do you have?", pt: "Quais bebidas vocês têm?" },
        { en: "Can I have a coffee with milk?", pt: "Posso querer um café com leite?" },
        { en: "I would like it medium rare.", pt: "Quero malpassado." },
        { en: "This is not what I ordered.", pt: "Isso não foi o que pedi." },
        { en: "Can I speak to the manager?", pt: "Posso falar com o gerente?" },
        { en: "Can we sit outside?", pt: "Podemos sentar do lado de fora?" },
        { en: "What are today is specials?", pt: "Quais são os especiais de hoje?" },
        { en: "I am vegetarian.", pt: "Sou vegetariano." },
        { en: "I am full, thank you.", pt: "Estou satisfeito, obrigado." },
        { en: "That will be all, thanks.", pt: "Isso é tudo, obrigado." },
        { en: "Excuse me, we are ready to order.", pt: "Com licença, estamos prontos para pedir." },
        { en: "Could I get a refill?", pt: "Posso pedir uma recarga?" },
        { en: "Can I have it without sugar?", pt: "Posso pedir sem açúcar?" },
        { en: "Does it come with fries?", pt: "Vem com batatas fritas?" },
        { en: "I would like some dessert.", pt: "Gostaria de uma sobremesa." },
        { en: "What kind of soup is it?", pt: "Que tipo de sopa é?" },
        { en: "Do you have any vegan options?", pt: "Vocês têm opções veganas?" }
    ],

    minhaRotina: [
        { en: "I wake up at 7 a.m.", pt: "Eu acordo às 7 da manhã." },
        { en: "I brush my teeth.", pt: "Eu escovo meus dentes." },
        { en: "I take a shower.", pt: "Eu tomo banho." },
        { en: "I get dressed.", pt: "Eu me visto." },
        { en: "I have breakfast.", pt: "Eu tomo café da manhã." },
        { en: "I go to work.", pt: "Eu vou para o trabalho." },
        { en: "I check my emails.", pt: "Eu verifico meus e-mails." },
        { en: "I attend meetings.", pt: "Eu participo de reuniões." },
        { en: "I take a lunch break.", pt: "Eu faço uma pausa para o almoço." },
        { en: "I return home.", pt: "Eu volto para casa." },
        { en: "I cook dinner.", pt: "Eu cozinho o jantar." },
        { en: "I watch TV.", pt: "Eu assisto TV." },
        { en: "I read a book.", pt: "Eu leio um livro." },
        { en: "I go for a walk.", pt: "Eu dou uma caminhada." },
        { en: "I go to the gym.", pt: "Eu vou à academia." },
        { en: "I listen to music.", pt: "Eu escuto música." },
        { en: "I do the dishes.", pt: "Eu lavo a louça." },
        { en: "I clean the house.", pt: "Eu limpo a casa." },
        { en: "I talk to my family.", pt: "Eu converso com minha família." },
        { en: "I feed the dog.", pt: "Eu alimento o cachorro." },
        { en: "I study English.", pt: "Eu estudo inglês." },
        { en: "I go to sleep at 10 p.m.", pt: "Eu durmo às 10 da noite." },
        { en: "I take a nap.", pt: "Eu tiro um cochilo." },
        { en: "I write in my journal.", pt: "Eu escrevo no meu diário." },
        { en: "I check social media.", pt: "Eu checo as redes sociais." },
        { en: "I iron my clothes.", pt: "Eu passo minhas roupas." },
        { en: "I take public transport.", pt: "Eu pego transporte público." },
        { en: "I work from home.", pt: "Eu trabalho de casa." },
        { en: "I prepare my things for tomorrow.", pt: "Eu preparo minhas coisas para amanhã." },
        { en: "I brush my hair.", pt: "Eu penteio meu cabelo." }
    ],

    meApresentado: [
        { en: "Hi, my name is...", pt: "Oi, meu nome é..." },
        { en: "I am from Brazil.", pt: "Sou do Brasil." },
        { en: "I am 25 years old.", pt: "Tenho 25 anos." },
        { en: "Nice to meet you.", pt: "Prazer em conhecê-lo." },
        { en: "Where are you from?", pt: "De onde você é?" },
        { en: "What do you do?", pt: "O que você faz?" },
        { en: "I am a student.", pt: "Sou estudante." },
        { en: "I work as a teacher.", pt: "Trabalho como professor." },
        { en: "I live in São Paulo.", pt: "Eu moro em São Paulo." },
        { en: "This is my first time here.", pt: "É minha primeira vez aqui." },
        { en: "I love learning languages.", pt: "Adoro aprender idiomas." },
        { en: "Do you speak English?", pt: "Você fala inglês?" },
        { en: "I am learning English.", pt: "Estou aprendendo inglês." },
        { en: "Can you repeat that?", pt: "Pode repetir isso?" },
        { en: "Please speak slowly.", pt: "Por favor, fale devagar." },
        { en: "I'm married.", pt: "Sou casado." },
        { en: "I'm single.", pt: "Sou solteiro." },
        { en: "I have two brothers.", pt: "Tenho dois irmãos." },
        { en: "I enjoy music and movies.", pt: "Gosto de música e filmes." },
        { en: "I am here on vacation.", pt: "Estou aqui de férias." },
        { en: "I am here for work.", pt: "Estou aqui a trabalho." },
        { en: "I have a dog named Rex.", pt: "Tenho um cachorro chamado Rex." },
        { en: "I love traveling.", pt: "Adoro viajar." },
        { en: "How long have you been here?", pt: "Há quanto tempo você está aqui?" },
        { en: "I am excited to be here.", pt: "Estou empolgado por estar aqui." },
        { en: "Can I add you on social media?", pt: "Posso te adicionar nas redes sociais?" },
        { en: "Do you have WhatsApp?", pt: "Você tem WhatsApp?" },
        { en: "What is your name again?", pt: "Qual é mesmo o seu nome?" },
        { en: "Could you spell that?", pt: "Pode soletrar isso?" },
        { en: "What do you like to do?", pt: "O que você gosta de fazer?" }
    ],

    batePapo: [
    { en: "How is it going?", pt: "Como vai?" },
    { en: "What is up?", pt: "E aí?" },
    { en: "Long time no see!", pt: "Quanto tempo!" },
    { en: "What have you been up to?", pt: "O que você tem feito?" },
    { en: "Just chilling.", pt: "Só relaxando." },
    { en: "Not much.", pt: "Nada demais." },
    { en: "Do you want to hang out?", pt: "Quer sair?" },
    { en: "Let is grab a coffee.", pt: "Vamos tomar um café." },
    { en: "What time is good for you?", pt: "Qual horário é bom pra você?" },
    { en: "I will text you later.", pt: "Te mando mensagem depois." },
    { en: "Call me when you are free.", pt: "Me liga quando estiver livre." },
    { en: "Can we talk?", pt: "Podemos conversar?" },
    { en: "It is been a busy day.", pt: "Foi um dia corrido." },
    { en: "I am tired today.", pt: "Estou cansado hoje." },
    { en: "You look great!", pt: "Você está ótimo!" },
    { en: "I missed you.", pt: "Senti sua falta." },
    { en: "Same here!", pt: "Igualmente!" },
    { en: "That is funny!", pt: "Isso é engraçado!" },
    { en: "Really? Tell me more.", pt: "Sério? Me conta mais." },
    { en: "That makes sense.", pt: "Faz sentido." },
    { en: "You are right.", pt: "Você tem razão." },
    { en: "Exactly!", pt: "Exatamente!" },
    { en: "I totally agree.", pt: "Concordo totalmente." },
    { en: "I see what you mean.", pt: "Entendi o que você quer dizer." },
    { en: "Let is change the subject.", pt: "Vamos mudar de assunto." },
    { en: "It is a nice day today.", pt: "Hoje está um dia bonito." },
    { en: "Did you hear about...?", pt: "Você soube sobre...?" },
    { en: "I am so happy for you!", pt: "Estou tão feliz por você!" },
    { en: "That is awesome!", pt: "Isso é incrível!" },
    { en: "Let is keep in touch.", pt: "Vamos manter contato." }
  ],

  Compras: [
    { en: "How much is this?", pt: "Quanto custa isso?" },
    { en: "Do you have this in another size?", pt: "Você tem isso em outro tamanho?" },
    { en: "Do you have this in blue?", pt: "Você tem isso em azul?" },
    { en: "Can I try it on?", pt: "Posso experimentar?" },
    { en: "Where is the fitting room?", pt: "Onde fica o provador?" },
    { en: "I am just looking, thanks.", pt: "Estou só olhando, obrigado." },
    { en: "I will take this one.", pt: "Vou levar esse." },
    { en: "Can I pay by card?", pt: "Posso pagar com cartão?" },
    { en: "Is it on sale?", pt: "Está na promoção?" },
    { en: "Do you offer refunds?", pt: "Vocês oferecem reembolso?" },
    { en: "Can I exchange this?", pt: "Posso trocar isso?" },
    { en: "What is your return policy?", pt: "Qual é a política de devolução?" },
    { en: "I am looking for a gift.", pt: "Estou procurando um presente." },
    { en: "Do you have a receipt?", pt: "Você tem recibo?" },
    { en: "Do you sell electronics?", pt: "Vocês vendem eletrônicos?" },
    { en: "I need a new phone charger.", pt: "Preciso de um novo carregador de celular." },
    { en: "Where can I find groceries?", pt: "Onde posso encontrar mantimentos?" },
    { en: "Can I see that one?", pt: "Posso ver aquele?" },
    { en: "This is too expensive.", pt: "Isso é muito caro." },
    { en: "Can you lower the price?", pt: "Pode fazer um desconto?" },
    { en: "I would like a bag, please.", pt: "Gostaria de uma sacola, por favor." },
    { en: "Where is the cashier?", pt: "Onde fica o caixa?" },
    { en: "I do not need a bag, thanks.", pt: "Não preciso de sacola, obrigado." },
    { en: "Do you take cash?", pt: "Aceitam dinheiro?" },
    { en: "Is this the final price?", pt: "Esse é o preço final?" },
    { en: "Can I use a coupon?", pt: "Posso usar um cupom?" },
    { en: "I want to return this item.", pt: "Quero devolver esse item." },
    { en: "Do you sell clothes here?", pt: "Vocês vendem roupas aqui?" },
    { en: "What is the price of this shirt?", pt: "Qual o preço dessa camisa?" },
    { en: "This does not fit me.", pt: "Isso não serve em mim." }
  ],

  Viajando: [
    { en: "Where is the nearest hotel?", pt: "Onde fica o hotel mais próximo?" },
    { en: "Can I book a room?", pt: "Posso reservar um quarto?" },
    { en: "Do you have free Wi-Fi?", pt: "Tem Wi-Fi gratuito?" },
    { en: "What time is check-out?", pt: "Qual o horário do check-out?" },
    { en: "Where can I get a taxi?", pt: "Onde posso pegar um táxi?" },
    { en: "How much is the fare?", pt: "Quanto é a corrida?" },
    { en: "I would like a one-way ticket.", pt: "Quero um bilhete só de ida." },
    { en: "I would like a round-trip ticket.", pt: "Quero um bilhete de ida e volta." },
    { en: "What time does the train leave?", pt: "Que horas o trem sai?" },
    { en: "Is this seat taken?", pt: "Esse assento está ocupado?" },
    { en: "How do I get to the airport?", pt: "Como faço para chegar ao aeroporto?" },
    { en: "Is there a bathroom on board?", pt: "Tem banheiro a bordo?" },
    { en: "How long is the flight?", pt: "Quanto tempo dura o voo?" },
    { en: "Can I see your passport?", pt: "Posso ver seu passaporte?" },
    { en: "Do I need a visa?", pt: "Preciso de visto?" },
    { en: "I am here on vacation.", pt: "Estou aqui de férias." },
    { en: "Where is baggage claim?", pt: "Onde fica a esteira de bagagens?" },
    { en: "My luggage is lost.", pt: "Minha bagagem está perdida." },
    { en: "Where can I rent a car?", pt: "Onde posso alugar um carro?" },
    { en: "I would like to rent a car.", pt: "Gostaria de alugar um carro." },
    { en: "Do I need insurance?", pt: "Preciso de seguro?" },
    { en: "Can I see the map?", pt: "Posso ver o mapa?" },
    { en: "Where is the city center?", pt: "Onde fica o centro da cidade?" },
    { en: "I am looking for a museum.", pt: "Estou procurando um museu." },
    { en: "Is this place safe?", pt: "Este lugar é seguro?" },
    { en: "What is a good place to eat?", pt: "Qual um bom lugar para comer?" },
    { en: "Do you have a reservation?", pt: "Você tem reserva?" },
    { en: "Where is the bus stop?", pt: "Onde fica o ponto de ônibus?" },
    { en: "I need help, please.", pt: "Preciso de ajuda, por favor." },
    { en: "Call the police!", pt: "Chame a polícia!" }
  ]
}

export default spokenContent;