const spokenContent = {

  comerFora: [
    { "en": "I would like a table for two, please.", "pt": "Gostaria de uma mesa para dois, por favor.", "es": "Me gustaría una mesa para dos, por favor.", "fr": "Je voudrais une table pour deux, s'il vous plaît." },
    { "en": "Can I see the menu?", "pt": "Posso ver o cardápio?", "es": "¿Puedo ver el menú?", "fr": "Puis-je voir le menu ?" },
    { "en": "I will have the chicken, please.", "pt": "Vou querer o frango, por favor.", "es": "Voy a tomar el pollo, por favor.", "fr": "Je vais prendre le poulet, s'il vous plaît." },
    { "en": "What do you recommend?", "pt": "O que você recomenda?", "es": "¿Qué recomienda?", "fr": "Que recommandez-vous ?" },
    { "en": "Can I get this without onions?", "pt": "Posso pedir isso sem cebolas?", "es": "¿Puedo pedir esto sin cebolla?", "fr": "Puis-je avoir ceci sans oignons ?" },
    { "en": "I am allergic to peanuts.", "pt": "Sou alérgico a amendoim.", "es": "Soy alérgico a los cacahuetes.", "fr": "Je suis allergique aux arachides." },
    { "en": "Is this dish spicy?", "pt": "Esse prato é apimentado?", "es": "¿Este plato es picante?", "fr": "Ce plat est-il épicé ?" },
    { "en": "Can we have separate checks?", "pt": "Podemos ter contas separadas?", "es": "¿Podemos tener cuentas separadas?", "fr": "Pouvons-nous avoir des additions séparées ?" },
    { "en": "Just water for me, thanks.", "pt": "Só água para mim, obrigado.", "es": "Solo agua para mí, gracias.", "fr": "Juste de l'eau pour moi, merci." },
    { "en": "Can I get this to go?", "pt": "Posso pedir para viagem?", "es": "¿Puedo llevar esto para llevar?", "fr": "Puis-je l'emporter ?" },
    { "en": "Can I get the bill, please?", "pt": "Posso pedir a conta, por favor?", "es": "¿Me puede traer la cuenta, por favor?", "fr": "Puis-je avoir l'addition, s'il vous plaît ?" },
    { "en": "That was delicious!", "pt": "Estava delicioso!", "es": "¡Estaba delicioso!", "fr": "C'était délicieux !" },
    { "en": "Do you take credit cards?", "pt": "Vocês aceitam cartões de crédito?", "es": "¿Aceptan tarjetas de crédito?", "fr": "Acceptez-vous les cartes de crédit ?" },
    { "en": "What drinks do you have?", "pt": "Quais bebidas vocês têm?", "es": "¿Qué bebidas tienen?", "fr": "Quelles boissons avez-vous ?" },
    { "en": "Can I have a coffee with milk?", "pt": "Posso querer um café com leite?", "es": "¿Puedo tomar un café con leche?", "fr": "Puis-je avoir un café au lait ?" },
    { "en": "I would like it medium rare.", "pt": "Quero malpassado.", "es": "Lo quiero a medio cocer.", "fr": "Je le voudrais à point." },
    { "en": "This is not what I ordered.", "pt": "Isso não foi o que pedi.", "es": "Esto no es lo que pedí.", "fr": "Ce n'est pas ce que j'ai commandé." },
    { "en": "Can I speak to the manager?", "pt": "Posso falar com o gerente?", "es": "¿Puedo hablar con el gerente?", "fr": "Puis-je parler au gérant ?" },
    { "en": "Can we sit outside?", "pt": "Podemos sentar do lado de fora?", "es": "¿Podemos sentarnos afuera?", "fr": "Pouvons-nous nous asseoir à l'extérieur ?" },
    { "en": "What are today is specials?", "pt": "Quais são os especiais de hoje?", "es": "¿Cuáles son los especiales de hoy?", "fr": "Quels sont les plats du jour ?" },
    { "en": "I am vegetarian.", "pt": "Sou vegetariano.", "es": "Soy vegetariano.", "fr": "Je suis végétarien." },
    { "en": "I am full, thank you.", "pt": "Estou satisfeito, obrigado.", "es": "Estoy lleno, gracias.", "fr": "Je suis rassasié, merci." },
    { "en": "That will be all, thanks.", "pt": "Isso é tudo, obrigado.", "es": "Eso es todo, gracias.", "fr": "Ce sera tout, merci." },
    { "en": "Excuse me, we are ready to order.", "pt": "Com licença, estamos prontos para pedir.", "es": "Disculpe, estamos listos para ordenar.", "fr": "Excusez-moi, nous sommes prêts à commander." },
    { "en": "Could I get a refill?", "pt": "Posso pedir uma recarga?", "es": "¿Podría rellenar mi vaso?", "fr": "Pourrais-je avoir un rab ?" },
    { "en": "Can I have it without sugar?", "pt": "Posso pedir sem açúcar?", "es": "¿Lo puedo tener sin azúcar?", "fr": "Puis-je l'avoir sans sucre ?" },
    { "en": "Does it come with fries?", "pt": "Vem com batatas fritas?", "es": "¿Viene con papas fritas?", "fr": "Est-ce que ça vient avec des frites ?" },
    { "en": "I would like some dessert.", "pt": "Gostaria de uma sobremesa.", "es": "Me gustaría un postre.", "fr": "Je voudrais un dessert." },
    { "en": "What kind of soup is it?", "pt": "Que tipo de sopa é?", "es": "¿Qué tipo de sopa es?", "fr": "Quel genre de soupe est-ce ?" },
    { "en": "Do you have any vegan options?", "pt": "Vocês têm opções veganas?", "es": "¿Tienen opciones veganas?", "fr": "Avez-vous des options véganes ?" }
  ],
  minhaRotina: [
    { "en": "I wake up at 7 a.m.", "pt": "Eu acordo às 7 da manhã.", "es": "Me despierto a las 7 de la mañana.", "fr": "Je me réveille à 7 heures du matin." },
    { "en": "I brush my teeth.", "pt": "Eu escovo meus dentes.", "es": "Me cepillo los dientes.", "fr": "Je me brosse les dents." },
    { "en": "I take a shower.", "pt": "Eu tomo banho.", "es": "Me ducho.", "fr": "Je prends une douche." },
    { "en": "I get dressed.", "pt": "Eu me visto.", "es": "Me visto.", "fr": "Je m'habille." },
    { "en": "I have breakfast.", "pt": "Eu tomo café da manhã.", "es": "Desayuno.", "fr": "Je prends le petit déjeuner." },
    { "en": "I go to work.", "pt": "Eu vou para o trabalho.", "es": "Voy al trabajo.", "fr": "Je vais au travail." },
    { "en": "I check my emails.", "pt": "Eu verifico meus e-mails.", "es": "Reviso mis correos electrónicos.", "fr": "Je vérifie mes e-mails." },
    { "en": "I attend meetings.", "pt": "Eu participo de reuniões.", "es": "Asisto a reuniones.", "fr": "Je participe à des réunions." },
    { "en": "I take a lunch break.", "pt": "Eu faço uma pausa para o almoço.", "es": "Tomo un descanso para almorzar.", "fr": "Je fais une pause déjeuner." },
    { "en": "I return home.", "pt": "Eu volto para casa.", "es": "Regreso a casa.", "fr": "Je rentre à la maison." },
    { "en": "I cook dinner.", "pt": "Eu cozinho o jantar.", "es": "Preparo la cena.", "fr": "Je prépare le dîner." },
    { "en": "I watch TV.", "pt": "Eu assisto TV.", "es": "Veo la televisión.", "fr": "Je regarde la télévision." },
    { "en": "I read a book.", "pt": "Eu leio um livro.", "es": "Leo un libro.", "fr": "Je lis un livre." },
    { "en": "I go for a walk.", "pt": "Eu dou uma caminhada.", "es": "Salgo a caminar.", "fr": "Je fais une promenade." },
    { "en": "I go to the gym.", "pt": "Eu vou à academia.", "es": "Voy al gimnasio.", "fr": "Je vais à la salle de sport." },
    { "en": "I listen to music.", "pt": "Eu escuto música.", "es": "Escucho música.", "fr": "J'écoute de la musique." },
    { "en": "I do the dishes.", "pt": "Eu lavo a louça.", "es": "Lavo los platos.", "fr": "Je fais la vaisselle." },
    { "en": "I clean the house.", "pt": "Eu limpo a casa.", "es": "Limpio la casa.", "fr": "Je nettoie la maison." },
    { "en": "I talk to my family.", "pt": "Eu converso com minha família.", "es": "Hablo con mi familia.", "fr": "Je parle à ma famille." },
    { "en": "I feed the dog.", "pt": "Eu alimento o cachorro.", "es": "Alimento al perro.", "fr": "Je nourris le chien." },
    { "en": "I study English.", "pt": "Eu estudo inglês.", "es": "Estudio inglés.", "fr": "J'étudie l'anglais." },
    { "en": "I go to sleep at 10 p.m.", "pt": "Eu durmo às 10 da noite.", "es": "Me acuesto a las 10 de la noche.", "fr": "Je vais me coucher à 22 heures." },
    { "en": "I take a nap.", "pt": "Eu tiro um cochilo.", "es": "Tomo una siesta.", "fr": "Je fais une sieste." },
    { "en": "I write in my journal.", "pt": "Eu escrevo no meu diário.", "es": "Escribo en mi diario.", "fr": "J'écris dans mon journal." },
    { "en": "I check social media.", "pt": "Eu checo as redes sociais.", "es": "Reviso las redes sociales.", "fr": "Je consulte les réseaux sociaux." },
    { "en": "I iron my clothes.", "pt": "Eu passo minhas roupas.", "es": "Plancho mi ropa.", "fr": "Je repasse mes vêtements." },
    { "en": "I take public transport.", "pt": "Eu pego transporte público.", "es": "Tomo transporte público.", "fr": "Je prends les transports en commun." },
    { "en": "I work from home.", "pt": "Eu trabalho de casa.", "es": "Trabajo desde casa.", "fr": "Je travaille à domicile." },
    { "en": "I prepare my things for tomorrow.", "pt": "Eu preparo minhas coisas para amanhã.", "es": "Preparo mis cosas para mañana.", "fr": "Je prépare mes affaires pour demain." },
    { "en": "I brush my hair.", "pt": "Eu penteio meu cabelo.", "es": "Me cepillo el pelo.", "fr": "Je me brosse les cheveux." }
  ],
  meApresentando: [
    { "en": "Hi, my name is...", "pt": "Oi, meu nome é...", "es": "Hola, mi nombre es...", "fr": "Bonjour, je m'appelle..." },
    { "en": "I am from Brazil.", "pt": "Sou do Brasil.", "es": "Soy de Brasil.", "fr": "Je viens du Brésil." },
    { "en": "I am 25 years old.", "pt": "Tenho 25 anos.", "es": "Tengo 25 años.", "fr": "J'ai 25 ans." },
    { "en": "Nice to meet you.", "pt": "Prazer em conhecê-lo.", "es": "Mucho gusto.", "fr": "Enchanté de faire votre connaissance." },
    { "en": "Where are you from?", "pt": "De onde você é?", "es": "¿De dónde eres?", "fr": "D'où venez-vous ?" },
    { "en": "What do you do?", "pt": "O que você faz?", "es": "¿A qué te dedicas?", "fr": "Que faites-vous dans la vie ?" },
    { "en": "I am a student.", "pt": "Sou estudante.", "es": "Soy estudiante.", "fr": "Je suis étudiant." },
    { "en": "I work as a teacher.", "pt": "Trabalho como professor.", "es": "Trabajo como profesor.", "fr": "Je travaille comme professeur." },
    { "en": "I live in São Paulo.", "pt": "Eu moro em São Paulo.", "es": "Vivo en São Paulo.", "fr": "Je vis à São Paulo." },
    { "en": "This is my first time here.", "pt": "É minha primeira vez aqui.", "es": "Es mi primera vez aquí.", "fr": "C'est ma première fois ici." },
    { "en": "I love learning languages.", "pt": "Adoro aprender idiomas.", "es": "Me encanta aprender idiomas.", "fr": "J'adore apprendre des langues." },
    { "en": "Do you speak English?", "pt": "Você fala inglês?", "es": "¿Hablas inglés?", "fr": "Parlez-vous anglais ?" },
    { "en": "I am learning English.", "pt": "Estou aprendendo inglês.", "es": "Estoy aprendiendo inglés.", "fr": "J'apprends l'anglais." },
    { "en": "Can you repeat that?", "pt": "Pode repetir isso?", "es": "¿Puedes repetir eso?", "fr": "Pouvez-vous répéter cela ?" },
    { "en": "Please speak slowly.", "pt": "Por favor, fale devagar.", "es": "Por favor, habla despacio.", "fr": "Parlez lentement, s'il vous plaît." },
    { "en": "I'm married.", "pt": "Sou casado.", "es": "Estoy casado.", "fr": "Je suis marié." },
    { "en": "I'm single.", "pt": "Sou solteiro.", "es": "Soy soltero.", "fr": "Je suis célibataire." },
    { "en": "I have two brothers.", "pt": "Tenho dois irmãos.", "es": "Tengo dos hermanos.", "fr": "J'ai deux frères." },
    { "en": "I enjoy music and movies.", "pt": "Gosto de música e filmes.", "es": "Disfruto de la música y las películas.", "fr": "J'aime la musique et les films." },
    { "en": "I am here on vacation.", "pt": "Estou aqui de férias.", "es": "Estoy aquí de vacaciones.", "fr": "Je suis ici en vacances." },
    { "en": "I am here for work.", "pt": "Estou aqui a trabalho.", "es": "Estoy aquí por trabajo.", "fr": "Je suis ici pour le travail." },
    { "en": "I have a dog named Rex.", "pt": "Tenho um cachorro chamado Rex.", "es": "Tengo un perro llamado Rex.", "fr": "J'ai un chien qui s'appelle Rex." },
    { "en": "I love traveling.", "pt": "Adoro viajar.", "es": "Me encanta viajar.", "fr": "J'adore voyager." },
    { "en": "How long have you been here?", "pt": "Há quanto tempo você está aqui?", "es": "¿Cuánto tiempo llevas aquí?", "fr": "Depuis combien de temps êtes-vous ici ?" },
    { "en": "I am excited to be here.", "pt": "Estou empolgado por estar aqui.", "es": "Estoy emocionado de estar aquí.", "fr": "Je suis ravi d'être ici." },
    { "en": "Can I add you on social media?", "pt": "Posso te adicionar nas redes sociais?", "es": "¿Puedo agregarte en redes sociales?", "fr": "Puis-je vous ajouter sur les réseaux sociaux ?" },
    { "en": "Do you have WhatsApp?", "pt": "Você tem WhatsApp?", "es": "¿Tienes WhatsApp?", "fr": "Avez-vous WhatsApp ?" },
    { "en": "What is your name again?", "pt": "Qual é mesmo o seu nome?", "es": "¿Cuál es tu nombre?", "fr": "Quel est votre nom déjà ?" },
    { "en": "Could you spell that?", "pt": "Pode soletrar isso?", "es": "¿Puedes deletrearlo?", "fr": "Pouvez-vous l'épeler ?" },
    { "en": "What do you like to do?", "pt": "O que você gosta de fazer?", "es": "¿Qué te gusta hacer?", "fr": "Qu'aimez-vous faire ?" }
  ],
  batePapo: [
    { "en": "How is it going?", "pt": "Como vai?", "es": "¿Cómo va todo?", "fr": "Comment ça va ?" },
    { "en": "What is up?", "pt": "E aí?", "es": "¿Qué tal?", "fr": "Quoi de neuf ?" },
    { "en": "Long time no see!", "pt": "Quanto tempo!", "es": "¡Cuánto tiempo sin verte!", "fr": "Ça fait longtemps !" },
    { "en": "What have you been up to?", "pt": "O que você tem feito?", "es": "¿Qué has estado haciendo?", "fr": "Qu'as-tu fait depuis ?" },
    { "en": "Just chilling.", "pt": "Só relaxando.", "es": "Sólo relajándome.", "fr": "Je me détends." },
    { "en": "Not much.", "pt": "Nada demais.", "es": "No mucho.", "fr": "Pas grand-chose." },
    { "en": "Do you want to hang out?", "pt": "Quer sair?", "es": "¿Quieres salir?", "fr": "Tu veux sortir ?" },
    { "en": "Let is grab a coffee.", "pt": "Vamos tomar um café.", "es": "Vamos a tomar un café.", "fr": "Allons prendre un café." },
    { "en": "What time is good for you?", "pt": "Qual horário é bom pra você?", "es": "¿Qué hora te viene bien?", "fr": "Quelle heure te convient ?" },
    { "en": "I will text you later.", "pt": "Te mando mensagem depois.", "es": "Te mando un mensaje después.", "fr": "Je t'enverrai un message plus tard." },
    { "en": "Call me when you are free.", "pt": "Me liga quando estiver livre.", "es": "Llámame cuando estés libre.", "fr": "Appelle-moi quand tu es libre." },
    { "en": "Can we talk?", "pt": "Podemos conversar?", "es": "¿Podemos hablar?", "fr": "Pouvons-nous parler ?" },
    { "en": "It is been a busy day.", "pt": "Foi um dia corrido.", "es": "Ha sido un día ocupado.", "fr": "Ça a été une journée chargée." },
    { "en": "I am tired today.", "pt": "Estou cansado hoje.", "es": "Estoy cansado hoy.", "fr": "Je suis fatigué aujourd'hui." },
    { "en": "You look great!", "pt": "Você está ótimo!", "es": "¡Te ves genial!", "fr": "Tu as l'air super !" },
    { "en": "I missed you.", "pt": "Senti sua falta.", "es": "Te extrañé.", "fr": "Tu m'as manqué." },
    { "en": "Same here!", "pt": "Igualmente!", "es": "¡Igualmente!", "fr": "Pareillement !" },
    { "en": "That is funny!", "pt": "Isso é engraçado!", "es": "¡Eso es gracioso!", "fr": "C'est drôle !" },
    { "en": "Really? Tell me more.", "pt": "Sério? Me conta mais.", "es": "¿En serio? Cuéntame más.", "fr": "Vraiment ? Dis-m'en plus." },
    { "en": "That makes sense.", "pt": "Faz sentido.", "es": "Eso tiene sentido.", "fr": "C'est logique." },
    { "en": "You are right.", "pt": "Você tem razão.", "es": "Tienes razón.", "fr": "Tu as raison." },
    { "en": "Exactly!", "pt": "Exatamente!", "es": "¡Exactamente!", "fr": "Exactement !" },
    { "en": "I totally agree.", "pt": "Concordo totalmente.", "es": "Estoy totalmente de acuerdo.", "fr": "Je suis tout à fait d'accord." },
    { "en": "I see what you mean.", "pt": "Entendi o que você quer dizer.", "es": "Entiendo lo que quieres decir.", "fr": "Je vois ce que tu veux dire." },
    { "en": "Let is change the subject.", "pt": "Vamos mudar de assunto.", "es": "Cambiemos de tema.", "fr": "Changeons de sujet." },
    { "en": "It is a nice day today.", "pt": "Hoje está um dia bonito.", "es": "Hoy es un buen día.", "fr": "C'est une belle journée aujourd'hui." },
    { "en": "Did you hear about...?", "pt": "Você soube sobre...?", "es": "¿Escuchaste sobre...?", "fr": "As-tu entendu parler de... ?" },
    { "en": "I am so happy for you!", "pt": "Estou tão feliz por você!", "es": "¡Estoy tan feliz por ti!", "fr": "Je suis si heureux pour toi !" },
    { "en": "That is awesome!", "pt": "Isso é incrível!", "es": "¡Eso es increíble!", "fr": "C'est génial !" },
    { "en": "Let is keep in touch.", "pt": "Vamos manter contato.", "es": "Mantengámonos en contacto.", "fr": "Restons en contact." }
  ],
  Compras: [
    { "en": "How much is this?", "pt": "Quanto custa isso?", "es": "¿Cuánto cuesta esto?", "fr": "Combien ça coûte ?" },
    { "en": "Do you have this in another size?", "pt": "Você tem isso em outro tamanho?", "es": "¿Tienes esto en otra talla?", "fr": "Avez-vous ceci dans une autre taille ?" },
    { "en": "Do you have this in blue?", "pt": "Você tem isso em azul?", "es": "¿Tienes esto en azul?", "fr": "Avez-vous ceci en bleu ?" },
    { "en": "Can I try it on?", "pt": "Posso experimentar?", "es": "¿Me lo puedo probar?", "fr": "Puis-je l'essayer ?" },
    { "en": "Where is the fitting room?", "pt": "Onde fica o provador?", "es": "¿Dónde está el probador?", "fr": "Où est la cabine d'essayage ?" },
    { "en": "I am just looking, thanks.", "pt": "Estou só olhando, obrigado.", "es": "Sólo estoy mirando, gracias.", "fr": "Je regarde juste, merci." },
    { "en": "I will take this one.", "pt": "Vou levar esse.", "es": "Me llevaré este.", "fr": "Je vais prendre celui-ci." },
    { "en": "Can I pay by card?", "pt": "Posso pagar com cartão?", "es": "¿Puedo pagar con tarjeta?", "fr": "Puis-je payer par carte ?" },
    { "en": "Is it on sale?", "pt": "Está na promoção?", "es": "¿Está en oferta?", "fr": "Est-ce en solde ?" },
    { "en": "Do you offer refunds?", "pt": "Vocês oferecem reembolso?", "es": "¿Ofrecen reembolsos?", "fr": "Offrez-vous des remboursements ?" },
    { "en": "Can I exchange this?", "pt": "Posso trocar isso?", "es": "¿Puedo cambiar esto?", "fr": "Puis-je échanger ceci ?" },
    { "en": "What is your return policy?", "pt": "Qual é a política de devolução?", "es": "¿Cuál es su política de devolución?", "fr": "Quelle est votre politique de retour ?" },
    { "en": "I am looking for a gift.", "pt": "Estou procurando um presente.", "es": "Estoy buscando un regalo.", "fr": "Je cherche un cadeau." },
    { "en": "Do you have a receipt?", "pt": "Você tem recibo?", "es": "¿Tienes un recibo?", "fr": "Avez-vous un reçu ?" },
    { "en": "Do you sell electronics?", "pt": "Vocês vendem eletrônicos?", "es": "¿Venden electrónicos?", "fr": "Vendez-vous des appareils électroniques ?" },
    { "en": "I need a new phone charger.", "pt": "Preciso de um novo carregador de celular.", "es": "Necesito un nuevo cargador de teléfono.", "fr": "J'ai besoin d'un nouveau chargeur de téléphone." },
    { "en": "Where can I find groceries?", "pt": "Onde posso encontrar mantimentos?", "es": "¿Dónde puedo encontrar comestibles?", "fr": "Où puis-je trouver des produits d'épicerie ?" },
    { "en": "Can I see that one?", "pt": "Posso ver aquele?", "es": "¿Puedo ver ese?", "fr": "Puis-je voir celui-là ?" },
    { "en": "This is too expensive.", "pt": "Isso é muito caro.", "es": "Esto es demasiado caro.", "fr": "C'est trop cher." },
    { "en": "Can you lower the price?", "pt": "Pode fazer um desconto?", "es": "¿Puedes bajar el precio?", "fr": "Pouvez-vous baisser le prix ?" },
    { "en": "I would like a bag, please.", "pt": "Gostaria de uma sacola, por favor.", "es": "Me gustaría una bolsa, por favor.", "fr": "Je voudrais un sac, s'il vous plaît." },
    { "en": "Where is the cashier?", "pt": "Onde fica o caixa?", "es": "¿Dónde está la caja?", "fr": "Où est la caisse ?" },
    { "en": "I do not need a bag, thanks.", "pt": "Não preciso de sacola, obrigado.", "es": "No necesito bolsa, gracias.", "fr": "Je n'ai pas besoin de sac, merci." },
    { "en": "Do you take cash?", "pt": "Aceitam dinheiro?", "es": "¿Aceptan efectivo?", "fr": "Acceptez-vous l'argent liquide ?" },
    { "en": "Is this the final price?", "pt": "Esse é o preço final?", "es": "¿Este es el precio final?", "fr": "Est-ce le prix final ?" },
    { "en": "Can I use a coupon?", "pt": "Posso usar um cupom?", "es": "¿Puedo usar un cupón?", "fr": "Puis-je utiliser un coupon ?" },
    { "en": "I want to return this item.", "pt": "Quero devolver esse item.", "es": "Quiero devolver este artículo.", "fr": "Je veux retourner cet article." },
    { "en": "Do you sell clothes here?", "pt": "Vocês vendem roupas aqui?", "es": "¿Venden ropa aquí?", "fr": "Vendez-vous des vêtements ici ?" },
    { "en": "What is the price of this shirt?", "pt": "Qual o preço dessa camisa?", "es": "¿Cuál es el precio de esta camisa?", "fr": "Quel est le prix de cette chemise ?" },
    { "en": "This does not fit me.", "pt": "Isso não serve em mim.", "es": "Esto no me queda.", "fr": "Ça ne me va pas." }
  ],
  Viajando: [
    { "en": "Where is the nearest hotel?", "pt": "Onde fica o hotel mais próximo?", "es": "¿Dónde está el hotel más cercano?", "fr": "Où est l'hôtel le plus proche ?" },
    { "en": "Can I book a room?", "pt": "Posso reservar um quarto?", "es": "¿Puedo reservar una habitación?", "fr": "Puis-je réserver une chambre ?" },
    { "en": "Do you have free Wi-Fi?", "pt": "Tem Wi-Fi gratuito?", "es": "¿Tienes Wi-Fi gratis?", "fr": "Avez-vous le Wi-Fi gratuit ?" },
    { "en": "What time is check-out?", "pt": "Qual o horário do check-out?", "es": "¿A qué hora es el check-out?", "fr": "À quelle heure est le check-out ?" },
    { "en": "Where can I get a taxi?", "pt": "Onde posso pegar um táxi?", "es": "¿Dónde puedo conseguir un taxi?", "fr": "Où puis-je prendre un taxi ?" },
    { "en": "How much is the fare?", "pt": "Quanto é a corrida?", "es": "¿Cuánto cuesta el pasaje?", "fr": "Combien coûte le trajet ?" },
    { "en": "I would like a one-way ticket.", "pt": "Quero um bilhete só de ida.", "es": "Quiero un boleto de ida.", "fr": "Je voudrais un aller simple." },
    { "en": "I would like a round-trip ticket.", "pt": "Quero um bilhete de ida e volta.", "es": "Quiero un boleto de ida y vuelta.", "fr": "Je voudrais un aller-retour." },
    { "en": "What time does the train leave?", "pt": "Que horas o trem sai?", "es": "¿A qué hora sale el tren?", "fr": "À quelle heure part le train ?" },
    { "en": "Is this seat taken?", "pt": "Esse assento está ocupado?", "es": "¿Este asiento está ocupado?", "fr": "Ce siège est-il pris ?" },
    { "en": "How do I get to the airport?", "pt": "Como faço para chegar ao aeroporto?", "es": "¿Cómo llego al aeropuerto?", "fr": "Comment puis-je me rendre à l'aéroport ?" },
    { "en": "Is there a bathroom on board?", "pt": "Tem banheiro a bordo?", "es": "¿Hay baño a bordo?", "fr": "Y a-t-il des toilettes à bord ?" },
    { "en": "How long is the flight?", "pt": "Quanto tempo dura o voo?", "es": "¿Cuánto dura el vuelo?", "fr": "Combien de temps dure le vol ?" },
    { "en": "Can I see your passport?", "pt": "Posso ver seu passaporte?", "es": "¿Puedo ver tu pasaporte?", "fr": "Puis-je voir votre passeport ?" },
    { "en": "Do I need a visa?", "pt": "Preciso de visto?", "es": "¿Necesito visa?", "fr": "Ai-je besoin d'un visa ?" },
    { "en": "I am here on vacation.", "pt": "Estou aqui de férias.", "es": "Estoy aquí de vacaciones.", "fr": "Je suis ici en vacances." },
    { "en": "Where is baggage claim?", "pt": "Onde fica a esteira de bagagens?", "es": "¿Dónde está el reclamo de equipaje?", "fr": "Où est le retrait des bagages ?" },
    { "en": "My luggage is lost.", "pt": "Minha bagagem está perdida.", "es": "Mi equipaje está perdido.", "fr": "Mes bagages sont perdus." },
    { "en": "Where can I rent a car?", "pt": "Onde posso alugar um carro?", "es": "¿Dónde puedo alquilar un coche?", "fr": "Où puis-je louer une voiture ?" },
    { "en": "I would like to rent a car.", "pt": "Gostaria de alugar um carro.", "es": "Me gustaría alquilar un coche.", "fr": "Je voudrais louer une voiture." },
    { "en": "Do I need insurance?", "pt": "Preciso de seguro?", "es": "¿Necesito seguro?", "fr": "Ai-je besoin d'une assurance ?" },
    { "en": "Can I see the map?", "pt": "Posso ver o mapa?", "es": "¿Puedo ver el mapa?", "fr": "Puis-je voir la carte ?" },
    { "en": "Where is the city center?", "pt": "Onde fica o centro da cidade?", "es": "¿Dónde está el centro de la ciudad?", "fr": "Où est le centre-ville ?" },
    { "en": "I am looking for a museum.", "pt": "Estou procurando um museu.", "es": "Estoy buscando un museo.", "fr": "Je cherche un musée." },
    { "en": "Is this place safe?", "pt": "Este lugar é seguro?", "es": "¿Este lugar es seguro?", "fr": "Cet endroit est-il sûr ?" },
    { "en": "What is a good place to eat?", "pt": "Qual um bom lugar para comer?", "es": "¿Qué es un buen lugar para comer?", "fr": "Quel est un bon endroit pour manger ?" },
    { "en": "Do you have a reservation?", "pt": "Você tem reserva?", "es": "¿Tienes una reservación?", "fr": "Avez-vous une réservation ?" },
    { "en": "Where is the bus stop?", "pt": "Onde fica o ponto de ônibus?", "es": "¿Dónde está la parada de autobús?", "fr": "Où est l'arrêt de bus ?" },
    { "en": "I need help, please.", "pt": "Preciso de ajuda, por favor.", "es": "Necesito ayuda, por favor.", "fr": "J'ai besoin d'aide, s'il vous plaît." },
    { "en": "Call the police!", "pt": "Chame a polícia!", "es": "¡Llama a la policía!", "fr": "Appelez la police !" }
  ]
}

export default spokenContent;